import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { afterEach, describe, expect, it, vi } from "vitest";
import { GET as live } from "@/app/api/health/live/route";
import { GET as ready } from "@/app/api/health/ready/route";
import { assertProductionRuntimeSecurity } from "@/server/auth/session";
import { clientAddress } from "@/server/rate-limit";
import { structuredLog } from "@/server/observability";

const root=resolve(import.meta.dirname,"../../../.."); const file=(path:string)=>readFileSync(resolve(root,path),"utf8");
describe("production infrastructure contracts",()=>{
  afterEach(()=>vi.unstubAllEnvs());
  it("keeps public liveness and readiness responses minimal",async()=>{const l=await live();expect(await l.json()).toEqual({status:"ok"});const r=await ready();expect(r.status).toBe(200);expect(await r.json()).toEqual({status:"ready"});});
  it("binds production readiness to the exact app role, PostgreSQL 18, the baseline, and a healthy live or idle worker",()=>{const route=file("apps/web/src/app/api/health/ready/route.ts"),guards=file("prisma/postgresql/postgres-guards.sql");for(const token of ["assertProductionRuntimeSecurity","tempocove_app_login","runtime-role-unready","tempocove_readiness","runtime-dependencies-unready"])expect(route).toContain(token);for(const token of ["server_version_num","202608220100_production_baseline","WorkerHeartbeat","'STARTING','RUNNING','IDLE'"])expect(guards).toContain(token);});
  it("rejects SQLite and local process dependencies in production",()=>{vi.stubEnv("NODE_ENV","production");vi.stubEnv("NEXT_PUBLIC_APP_URL","https://example.com/");vi.stubEnv("AUTH_SECRET","production-auth-secret-at-least-thirty-two");vi.stubEnv("DATABASE_PROVIDER","sqlite");vi.stubEnv("DATABASE_URL","file:./dev.db");expect(()=>assertProductionRuntimeSecurity()).toThrow(/PostgreSQL/);});
  it("requires bounded database connection, concurrency pool, and statement timeouts before serving production",()=>{const source=file("apps/web/src/server/auth/session.ts"),database=file("apps/web/src/server/db.ts");for(const token of ["connect_timeout","pool_timeout","connection_limit","statement_timeout"])expect(source).toContain(token);for(const token of ["maxWait: 15_000","timeout: 30_000","contextualTransactionOptions"])expect(database).toContain(token);});
  it("pins images, separates worker and migration, and uses only external compose secrets",()=>{const docker=file("Dockerfile"),compose=file("compose.production.yml"),postgres=file("infrastructure/postgresql/Dockerfile");expect(docker).toMatch(/node:24\.\d+\.\d+-bookworm-slim@sha256:[0-9a-f]{64}/);expect(postgres).toMatch(/postgres:18\.6-bookworm@sha256:[0-9a-f]{64}/);expect(compose).toContain("dockerfile: infrastructure/postgresql/Dockerfile");expect(compose).toContain("target: migration");expect(compose).toContain("dist/worker.mjs");expect(compose).not.toMatch(/password:\s+[^$\n{]/i);expect((compose.match(/external: true/g)||[]).length).toBeGreaterThanOrEqual(10);});
  it("binds the generated PostgreSQL baseline to guard and least-privilege posture",()=>{const schema=file("prisma/postgresql/schema.prisma"),migration=file("prisma/postgresql/migrations/202608220100_production_baseline/migration.sql");expect(schema).toContain('provider = "postgresql"');for(const token of ["booking_workspace_guard","membership_last_owner_guard","oauth_admin_custody_guard","email_outbox_snapshot_immutable","REVOKE CREATE ON SCHEMA public","tempocove_worker"])expect(migration).toContain(token);});
  it("brokers public Google readiness without exposing credential tables and binds the production load to exact builds",()=>{const guards=file("prisma/postgresql/postgres-guards.sql"),calendar=file("apps/web/src/server/services/calendar.ts"),load=file("scripts/load-check.mts"),workflow=file(".github/workflows/ci.yml");for(const token of ["tempocove_public_google_ready","tempocove_public_google_credential","credential_member.role IN ('OWNER','ADMIN')"])expect(guards).toContain(token);expect(calendar).toContain("GOOGLE_CALENDAR_RETRY");expect(calendar).not.toMatch(/catch\s*\([^)]*\)\s*\{[^}]*return\s+this\.local/s);for(const token of ["LOAD_EXPECTED_BUILD_ID","sameSlotStatuses[409] !== 99","unexpectedErrorRate","heartbeat_build_id","LOAD_MISSING_EVENT_SLUG"])expect(load).toContain(token);expect(workflow).toContain("--build-arg BUILD_ID=${{ github.sha }}");});
  it("creates every native-load fixture identity in-workflow without ambient event variables",()=>{const workflow=file(".github/workflows/ci.yml"),fixture=file("scripts/postgres-load-fixture.mjs");for(const token of ["id: load-fixture","steps.load-fixture.outputs.event_slug","steps.load-fixture.outputs.missing_event_slug","steps.load-fixture.outputs.missing_duration_id","LOAD_FIXTURE_TOKEN_ENCRYPTION_KEY"])expect(workflow).toContain(token);expect(workflow).not.toMatch(/vars\.LOAD_(?:EVENT|DURATION|SECOND|MISSING|START)/);for(const token of ["event.workspaceId!==item.workspaceId","event.durations[0].eventTypeId!==event.id","Boolean(connection)","GITHUB_OUTPUT"])expect(fixture).toContain(token);});
  it("embeds one required build identity in web and worker artifacts and rejects mismatch before listening",()=>{const docker=file("Dockerfile"),compose=file("compose.production.yml"),worker=file("apps/web/src/server/worker.ts"),builder=file("scripts/build-worker.mjs"),instrumentation=file("apps/web/src/instrumentation.ts"),starter=file("scripts/start-web.mjs"),entrypoint=file("scripts/container-entrypoint.mjs"),nextConfig=file("apps/web/next.config.ts");expect(docker).toContain("required immutable BUILD_ID build argument missing or invalid");expect((compose.match(/args: \{ BUILD_ID:/g)||[]).length).toBe(2);expect((compose.match(/BUILD_ID: \$\{BUILD_ID:\?set immutable build identity\}/g)||[]).length).toBeGreaterThanOrEqual(2);expect(builder).toContain('"process.env.TEMPOCOVE_COMPILED_BUILD_ID"');expect(worker).toContain("const buildId = compiledBuildId");expect(worker).toContain("assertCompiledBuildIdentity()");expect(instrumentation).toContain("assertCompiledBuildIdentity()");expect(nextConfig).toContain("generateBuildId");for(const source of [starter,entrypoint])expect(source).toContain("before listening");});
  it("removes advisory-bearing optional build tooling from the runtime filesystem",()=>{const docker=file("Dockerfile"),checker=file("scripts/runtime-dependency-check.mjs"),workflow=file(".github/workflows/ci.yml"),policy=JSON.parse(file("infrastructure/dependency-audit-allowlist.json")) as {disposition:string};for(const token of ["node_modules/prisma","node_modules/@prisma/config","node_modules/deepmerge-ts","node_modules/effect","runtime-dependency-check.mjs"])expect(docker).toContain(token);for(const token of ["@prisma\\/config","deepmerge-ts","effect"])expect(checker).toContain(token);expect(workflow).toContain("scripts/runtime-dependency-check.mjs node_modules");expect(policy.disposition).toMatch(/production image removes.*chain/i);});
  it("imports claimable-sandbox Stripe profile credentials only into an ignored file without printing values",()=>{const importer=file("scripts/import-stripe-sandbox-profile.ps1"),ignore=file(".gitignore"),guide=file("docs/INTEGRATION-SETUP.md");for(const token of ["config --list @profileArguments","listen @profileArguments --print-secret","IsPathFullyQualified","@('--config', $canonicalConfig)","^rkcs_","^pk_test_","^whsec_",".env.stripe-sandbox.local"])expect(importer).toContain(token);expect(importer).not.toMatch(/Write-(?:Output|Host)\s+.*(?:secretKey|publishableKey|webhookSecret)/i);expect(ignore).toContain(".env.*.local");for(const token of ["sandbox create --project-name snagtime-qa-rotated --config $freshStripeConfig","-ConfigPath $freshStripeConfig","listen --project-name snagtime-qa-rotated --config $freshStripeConfig"])expect(guide).toContain(token);});
  it("drops untrusted proxy input and allowlist-redacts structured logs",()=>{vi.stubEnv("TRUST_PROXY","true");vi.stubEnv("PROXY_SHARED_SECRET","proxy-secret-that-is-at-least-thirty-two-bytes");const malformed=new Request("http://localhost",{headers:{"x-tempocove-proxy-secret":process.env.PROXY_SHARED_SECRET!,"x-forwarded-for":"not-an-ip, 203.0.113.1"}});expect(clientAddress(malformed)).toBe("global-untrusted-proxy");const write=vi.spyOn(process.stdout,"write").mockImplementation(()=>true);structuredLog("error",{event:"canary",authorization:"Bearer forbidden",password:"forbidden",code:"SAFE"});const output=String(write.mock.calls[0]?.[0]);expect(output).toContain("SAFE");expect(output).not.toContain("Bearer");expect(output).not.toContain("password");write.mockRestore();});
});
